
/** @typedef {Category[]} */
export const categories = [
  { id: 'mikveh', name: 'Mikveh', heName: 'מקווה', image: '' },
  { id: 'synagogue', name: 'Synagogue', heName: 'בית כנסת', image: '' },
  { id: 'chabad', name: 'Chabad House', heName: 'בית חב"ד', image: '' },
  { id: 'kosher_restaurant', name: 'Kosher Restaurant', heName: 'מסעדה כשרה', image: '' },
  { id: 'kosher_shop', name: 'Kosher Shop', heName: 'חנות כשרה', image: '' },
  { id: 'jewish_museum', name: 'Jewish Museum', heName: 'מוזיאון יהודי', image: '' },
  { id: 'cemetery', name: 'Jewish Cemetery', heName: 'בית קברות יהודי', image: '' },
  { id: 'holiday', name: 'Holiday Events', heName: 'אירועי חג', image: '' },
  { id: 'community_event', name: 'Community Event', heName: 'אירוע קהילתי', image: '' },
  { id: 'eruv', name: 'Eruv', heName: 'עירוב', image: '' },
  { id: 'jewish_tours', name: 'Jewish Tours', heName: 'סיורים יהודיים', image: '' },
  { id: 'jewish_hotel', name: 'Kosher Hotel', heName: 'מלון כשר', image: '' },
  { id: 'judaica_shop', name: 'Judaica Shop', heName: 'חנות יודאיקה', image: '' },
  { id: 'jewish_community_center', name: 'Jewish Community Center', heName: 'מרכז קהילתי יהודי', image: '' },
  { id: 'matzah_bakery', name: 'Matzah Bakery', heName: 'מאפיית מצות', image: '' },
  { id: 'succah_supplier', name: 'Sukkot Supplies', heName: 'ציוד לסוכה', image: '' },
  { id: 'brit_milah', name: 'Brit Milah Services', heName: 'שירותי ברית מילה', image: '' },
  { id: 'wedding_hall_kosher', name: 'Kosher Wedding Hall', heName: 'אולם חתונות כשר', image: '' },
  { id: 'rabbi_services', name: 'Rabbi Services', heName: 'שירותי רבנות', image: '' },
  { id: 'kosher_winery', name: 'Kosher Winery', heName: 'יקב כשר', image: '' },
  { id: 'jewish_counseling', name: 'Jewish Counseling', heName: 'ייעוץ יהודי', image: '' },
  { id: 'gemach', name: 'Gemach (Charity Lending)', heName: 'גמ"ח', image: '' },
  { id: 'kosher_catering', name: 'Kosher Catering', heName: 'קייטרינג כשר', image: '' },
  { id: 'shabbat_hospitality', name: 'Shabbat Hospitality', heName: 'אירוח שבת', image: '' },
  { id: 'kosher_supermarket', name: 'Kosher Supermarket', heName: 'סופר כשר', image: '' },
  { id: 'jewish_education', name: 'Jewish Education', heName: 'חינוך יהודי', image: '' },
  { id: 'kosher_bakery', name: 'Kosher Bakery', heName: 'מאפייה כשרה', image: '' },
  { id: 'kosher_butcher', name: 'Kosher Butcher', heName: 'קצביה כשרה', image: '' },
  { id: 'kosher_deli', name: 'Kosher Deli', heName: 'מעדנייה כשרה', image: '' },
  { id: 'kosher_grocery', name: 'Kosher Grocery', heName: 'מכולת כשרה', image: '' },
  { id: 'jewish_art_gallery', name: 'Jewish Art Gallery', heName: 'גלריה לאמנות יהודית', image: '' },
  { id: 'jewish_library', name: 'Jewish Library', heName: 'ספרייה יהודית', image: '' },
  { id: 'jewish_cultural_center', name: 'Jewish Cultural Center', heName: 'מרכז תרבות יהודי', image: '' },
  { id: 'other', name: 'Other', heName: 'אחר', image: '' },
];
